const translations = {
  pt: {
    navHome: "Início",
    navProjects: "Projetos",
    navRoadmap: "Roadmap",
    navAbout: "Sobre",
    navContact: "Contacto",

    heroEyebrow: "Laboratório digital independente",
    heroTitle: "PJCore Labs",
    heroSubtitle: "Software, IA, automação e ferramentas digitais criadas com propósito prático.",
    heroPrimary: "Ver projetos",
    heroSecondary: "Sobre o laboratório",

    aboutEyebrow: "Sobre",
    aboutTitle: "Uma casa para projetos digitais práticos.",
    aboutText: "A PJCore Labs é a marca central para projetos focados em produtividade, educação jurídica, automação, ferramentas de IA e sistemas pessoais de estação de trabalho.",

    projectsEyebrow: "Projetos",
    projectsTitle: "Projetos atuais e futuros",
    projectWorkstation: "Centro pessoal de controlo da estação de trabalho para monitorização, manutenção e produtividade.",
    projectSolicitadoria: "Repositório jurídico educativo criado com estrutura, disciplina e acesso público.",
    projectLeisUk: "Explicações claras sobre leis do Reino Unido para falantes de português, com fontes oficiais.",
    projectAiEncyclopedia: "Diretório de ferramentas de IA úteis, organizado para uso prático diário.",
    projectOrganizer: "Futuro sistema de organização pessoal para tarefas, notas, ideias e rotinas.",
    projectAiTools: "Pequenas ferramentas com IA pensadas para resolver problemas reais sem complexidade desnecessária.",

    customAppsEyebrow: "Apps à medida",
    customAppsTitle: "Pequenas ferramentas criadas para problemas reais.",
    customAppsText: "Nem todos os problemas precisam de uma aplicação gigante. Às vezes a resposta certa é um dashboard simples, um organizador, uma automatização ou uma ferramenta web feita à medida de uma necessidade concreta.",
    customAppsDashboardsTitle: "Dashboards",
    customAppsDashboardsText: "Painéis pessoais ou de projeto para ver informação útil num só lugar.",
    customAppsOrganizersTitle: "Organizadores",
    customAppsOrganizersText: "Sistemas simples para tarefas, projetos, notas, rotinas ou registos.",
    customAppsAutomationTitle: "Automação",
    customAppsAutomationText: "Pequenos scripts e fluxos de trabalho para reduzir trabalho manual repetitivo.",
    customAppsPrototypeTitle: "Protótipos",
    customAppsPrototypeText: "Primeiras versões de ideias, criadas para testar se são úteis antes de as tornar maiores.",
    customAppsButton: "Falar sobre uma ideia",

    valuesEyebrow: "Valores",
    valuesTitle: "Tecnologia simples, útil e honesta.",
    valuePracticalTitle: "Prática",
    valuePracticalText: "As ferramentas devem resolver problemas reais, não apenas parecer impressionantes.",
    valueTransparentTitle: "Transparente",
    valueTransparentText: "Os projetos devem ser compreensíveis, documentados e fáceis de verificar.",
    valueIndependentTitle: "Independente",
    valueIndependentText: "Construído passo a passo, sem depender de modas ou atalhos.",

    roadmapEyebrow: "Roadmap",
    roadmapTitle: "Próximos passos",
    roadmapOne: "Publicar a homepage oficial PJCore Labs v1.0.",
    roadmapTwo: "Ligar os projetos principais a páginas dedicadas.",
    roadmapThree: "Preparar os assets da marca, documentação e estrutura dos projetos.",
    roadmapFour: "Usar pjcorelabs.com como centro público dos futuros produtos digitais.",

    contactEyebrow: "Contacto",
    contactTitle: "Construir em silêncio. Publicar em condições.",
    contactText: "A PJCore Labs está em desenvolvimento ativo. Para contacto geral, usa o email oficial abaixo.",

    backProjects: "Voltar aos projetos",

    wsEyebrow: "Projeto",
    wsHeroSubtitle: "Sistema pessoal de controlo da estação de trabalho para monitorização, manutenção, produtividade e acesso rápido aos projetos locais.",
    wsOpenSiteButton: "Abrir site",
    wsPurposeEyebrow: "Propósito",
    wsPurposeTitle: "Um centro de controlo para a estação de trabalho.",
    wsPurposeText: "O Workstation OS foi pensado para centralizar a gestão diária de uma estação de trabalho Linux pessoal: estado do sistema, ações de manutenção, atalhos para projetos, acesso ao GitHub, ferramentas de produtividade e diagnósticos úteis.",
    wsStatusTitle: "Estado",
    wsStatusText: "Em desenvolvimento ativo.",
    wsFocusTitle: "Foco",
    wsFocusText: "Gestão prática da estação de trabalho, não uma substituição completa de sistema operativo.",
    wsPlatformTitle: "Plataforma",
    wsPlatformText: "Primeiro Linux, com dashboard no browser e ferramentas locais.",
    wsDirectionTitle: "Direção",
    wsDirectionText: "Interface simples, diagnósticos claros e acesso rápido às ações importantes.",
    wsFeaturesEyebrow: "Funcionalidades principais",
    wsFeaturesTitle: "O que está a ser construído.",
    wsFeatureSystemTitle: "Estado do sistema",
    wsFeatureSystemText: "CPU, RAM, disco, temperatura, internet e estado geral da máquina num só lugar.",
    wsFeatureMaintenanceTitle: "Manutenção",
    wsFeatureMaintenanceText: "Acesso rápido a scripts úteis, atualizações, verificações e futuras ações de reparação/diagnóstico.",
    wsFeatureLauncherTitle: "Lançador de projetos",
    wsFeatureLauncherText: "Acesso rápido a projetos locais ativos, pastas de desenvolvimento, repositórios GitHub e ferramentas.",
    wsFeatureDiagnosticsTitle: "Diagnósticos em linguagem simples",
    wsFeatureDiagnosticsText: "Informação técnica apresentada de forma útil, sem ficar enterrada em saída de terminal.",
    wsRoadmapEyebrow: "Roadmap",
    wsRoadmapTitle: "Próxima direção.",
    wsRoadmapOne: "Estabilizar a estrutura do dashboard e os cartões principais do sistema.",
    wsRoadmapTwo: "Melhorar os diagnósticos e tornar o estado técnico mais fácil de entender.",
    wsRoadmapThree: "Adicionar ações de manutenção mais seguras com confirmações claras.",
    wsRoadmapFour: "Ligar documentação do projeto, scripts e workflow GitHub.",
    wsRoadmapFive: "Preparar uma identidade de produto mais limpa dentro da PJCore Labs.",

    ppEyebrow: "Projetos",
    ppHeroTitle: "Ideias em realidade.",
    ppHeroSubtitle: "A PJCore Labs reúne projetos digitais práticos, ferramentas de aprendizagem, sistemas de automação e produtos experimentais.",
    ppPortfolioEyebrow: "Portefólio de projetos",
    ppPortfolioTitle: "Projetos principais",
    statusDevelopment: "Em desenvolvimento",
    statusOnline: "Online",
    statusPlanned: "Planeado",
    openProject: "Abrir projeto",
    ppWorkstationText: "Sistema pessoal de controlo da estação de trabalho para monitorização, manutenção, produtividade e acesso aos projetos locais.",
    ppSolicitadoriaText: "Repositório jurídico educativo independente em português, com aulas estruturadas, fontes legais e progressão académica.",
    ppLeisUkText: "Guia prático em português sobre leis do Reino Unido e informação pública, com fontes oficiais e avisos claros.",
    ppAiText: "Coleção organizada de ferramentas de IA úteis, pensada para uso prático, descoberta e consulta rápida.",

    rsEyebrow: "Projeto",
    rsHeroTitle: "Repositório de Solicitadoria",
    rsHeroSubtitle: "Repositório jurídico educativo independente em português, com aulas estruturadas, fontes legais e progressão académica.",
    rsOpenSiteButton: "Abrir site",
    rsPurposeEyebrow: "Propósito",
    rsPurposeTitle: "Um repositório jurídico estruturado para estudo.",
    rsPurposeText: "O Repositório de Solicitadoria organiza materiais de estudo jurídico, aulas, resumos, quizzes e fontes legais oficiais num percurso académico claro.",
    rsStatusTitle: "Estado",
    rsStatusText: "Online e em desenvolvimento ativo.",
    rsFocusTitle: "Foco",
    rsFocusText: "Educação jurídica em português, organizada por cadeiras, aulas e progressão de estudo.",
    rsDisclaimerTitle: "Posição legal",
    rsDisclaimerText: "Projeto apenas educativo. Não é aconselhamento jurídico e não substitui apoio jurídico qualificado.",
    rsDirectionTitle: "Direção",
    rsDirectionText: "Aulas mais claras, melhor navegação, fontes legais mais fortes e ferramentas práticas de revisão.",
    rsFeaturesEyebrow: "Funcionalidades principais",
    rsFeaturesTitle: "O que o projeto disponibiliza.",
    rsFeatureLessonsTitle: "Aulas estruturadas",
    rsFeatureLessonsText: "As cadeiras são organizadas em aulas, com progressão ao longo do percurso académico.",
    rsFeatureSourcesTitle: "Fontes legais",
    rsFeatureSourcesText: "São usadas referências legais oficiais e ligações às fontes para sustentar o material.",
    rsFeatureRevisionTitle: "Ferramentas de revisão",
    rsFeatureRevisionText: "Quizzes, resumos e páginas de apoio ajudam na revisão e consolidação.",
    rsFeatureProgressTitle: "Progressão académica",
    rsFeatureProgressText: "O repositório acompanha cadeiras, aulas e conclusão dentro do plano geral de estudo.",

    ukEyebrow: "Projeto",
    ukHeroTitle: "Leis UK para Portugueses",
    ukHeroSubtitle: "Guia prático em português sobre leis do Reino Unido e informação pública, com fontes oficiais e avisos claros.",
    ukPurposeEyebrow: "Propósito",
    ukPurposeTitle: "Informação jurídica clara do Reino Unido para falantes de português.",
    ukPurposeText: "Leis UK para Portugueses foi pensado para explicar informação jurídica pública do Reino Unido em português, usando fontes oficiais e linguagem prática.",
    ukStatusTitle: "Estado",
    ukStatusText: "Planeado e em preparação.",
    ukFocusTitle: "Foco",
    ukFocusText: "Informação pública do Reino Unido, regras legais e explicações práticas para leitores de língua portuguesa.",
    ukSourcesTitle: "Fontes",
    ukSourcesText: "O projeto dará prioridade a fontes oficiais, legislação e orientação de entidades públicas.",
    ukDisclaimerTitle: "Posição legal",
    ukDisclaimerText: "Informação apenas educativa. Não é aconselhamento jurídico e não substitui advogado, solicitor, adviser ou profissional qualificado.",
    ukFeaturesEyebrow: "Princípios principais",
    ukFeaturesTitle: "Como o projeto deve funcionar.",
    ukFeatureLanguageTitle: "Explicações em português",
    ukFeatureLanguageText: "Informação pública complexa deve ser explicada em português claro sem distorcer o significado legal.",
    ukFeatureOfficialTitle: "Referências oficiais",
    ukFeatureOfficialText: "Cada tema deve ligar diretamente à fonte oficial ou regra legal que está a ser explicada.",
    ukFeaturePracticalTitle: "Estrutura prática",
    ukFeaturePracticalText: "Os temas devem ser divididos em páginas menores, para cada regra ser explicada com cuidado e verificada corretamente.",
    ukFeatureHonestyTitle: "Limites claros",
    ukFeatureHonestyText: "O projeto deve separar claramente informação educativa de aconselhamento jurídico profissional.",

    aiEyebrow: "Projeto",
    aiHeroTitle: "AI Encyclopedia",
    aiHeroSubtitle: "Coleção organizada de ferramentas de IA úteis, pensada para uso prático, descoberta e consulta rápida.",
    aiOpenSiteButton: "Abrir site",
    aiPurposeEyebrow: "Propósito",
    aiPurposeTitle: "Um diretório prático de ferramentas de IA.",
    aiPurposeText: "A AI Encyclopedia organiza ferramentas úteis de inteligência artificial num espaço simples de consulta, descoberta, comparação e uso diário.",
    aiStatusTitle: "Estado",
    aiStatusText: "Online e disponível para uso público.",
    aiFocusTitle: "Foco",
    aiFocusText: "Ferramentas de IA úteis, organizadas por finalidade prática e não por moda.",
    aiUseTitle: "Caso de uso",
    aiUseText: "Descoberta rápida de ferramentas para escrita, código, produtividade, pesquisa, geração de imagens e aprendizagem.",
    aiDirectionTitle: "Direção",
    aiDirectionText: "Categorias mais limpas, melhores descrições, favoritos e recomendações práticas.",
    aiFeaturesEyebrow: "Funcionalidades principais",
    aiFeaturesTitle: "O que o projeto disponibiliza.",
    aiFeatureDirectoryTitle: "Diretório de ferramentas",
    aiFeatureDirectoryText: "Lista organizada de ferramentas de IA úteis, agrupadas para uso prático.",
    aiFeatureDiscoveryTitle: "Descoberta",
    aiFeatureDiscoveryText: "Uma forma rápida de encontrar ferramentas que podem ajudar em tarefas e fluxos de trabalho reais.",
    aiFeatureSimpleTitle: "Navegação simples",
    aiFeatureSimpleText: "O projeto mantém a interface direta, leve e fácil de explorar.",
    aiFeaturePracticalTitle: "Seleção prática",
    aiFeaturePracticalText: "O foco é utilidade, não colecionar todas as ferramentas que aparecem online.",

    footerText: "Todos os direitos reservados."
  },

  en: {
    navHome: "Home",
    navProjects: "Projects",
    navRoadmap: "Roadmap",
    navAbout: "About",
    navContact: "Contact",

    heroEyebrow: "Independent digital lab",
    heroTitle: "PJCore Labs",
    heroSubtitle: "Software, AI, automation and digital tools built with practical purpose.",
    heroPrimary: "View projects",
    heroSecondary: "About the lab",

    aboutEyebrow: "About",
    aboutTitle: "A home for practical digital projects.",
    aboutText: "PJCore Labs is the central brand for projects focused on productivity, legal education, automation, AI tools and personal workstation systems.",

    projectsEyebrow: "Projects",
    projectsTitle: "Current and future projects",
    projectWorkstation: "Personal workstation control centre for monitoring, maintenance and productivity.",
    projectSolicitadoria: "Educational legal repository built with structure, discipline and public access.",
    projectLeisUk: "Clear explanations of UK law for Portuguese speakers, with official sources.",
    projectAiEncyclopedia: "Directory of useful AI tools, organised for practical daily use.",
    projectOrganizer: "Future personal organisation system for tasks, notes, ideas and routines.",
    projectAiTools: "Small AI-powered tools designed to solve real problems without unnecessary complexity.",

    customAppsEyebrow: "Custom digital tools",
    customAppsTitle: "Small tools built for real problems.",
    customAppsText: "Not every problem needs a huge application. Sometimes the right answer is a simple dashboard, organiser, automation or web tool built around a specific need.",
    customAppsDashboardsTitle: "Dashboards",
    customAppsDashboardsText: "Personal or project dashboards to see useful information in one place.",
    customAppsOrganizersTitle: "Organisers",
    customAppsOrganizersText: "Simple systems for tasks, projects, notes, routines or records.",
    customAppsAutomationTitle: "Automation",
    customAppsAutomationText: "Small scripts and workflows to reduce repetitive manual work.",
    customAppsPrototypeTitle: "Prototypes",
    customAppsPrototypeText: "Early versions of ideas, built to test if they are useful before making them bigger.",
    customAppsButton: "Discuss an idea",

    valuesEyebrow: "Values",
    valuesTitle: "Simple, useful and honest technology.",
    valuePracticalTitle: "Practical",
    valuePracticalText: "Tools must solve real problems, not just look impressive.",
    valueTransparentTitle: "Transparent",
    valueTransparentText: "Projects should be understandable, documented and easy to verify.",
    valueIndependentTitle: "Independent",
    valueIndependentText: "Built step by step, without depending on hype or shortcuts.",

    roadmapEyebrow: "Roadmap",
    roadmapTitle: "Next steps",
    roadmapOne: "Publish the official PJCore Labs homepage v1.0.",
    roadmapTwo: "Connect the main projects with dedicated pages.",
    roadmapThree: "Prepare the brand assets, documentation and project structure.",
    roadmapFour: "Use pjcorelabs.com as the public centre for future digital products.",

    contactEyebrow: "Contact",
    contactTitle: "Building quietly. Publishing properly.",
    contactText: "PJCore Labs is under active development. For general contact, use the official email below.",

    backProjects: "Back to projects",

    wsEyebrow: "Project",
    wsHeroSubtitle: "A personal workstation control system for monitoring, maintenance, productivity and quick access to local projects.",
    wsOpenSiteButton: "Open website",
    wsPurposeEyebrow: "Purpose",
    wsPurposeTitle: "A control centre for the workstation.",
    wsPurposeText: "Workstation OS is designed to centralise the daily management of a personal Linux workstation: system status, maintenance actions, project shortcuts, GitHub access, productivity tools and useful diagnostics.",
    wsStatusTitle: "Status",
    wsStatusText: "In active development.",
    wsFocusTitle: "Focus",
    wsFocusText: "Practical workstation management, not a full operating system replacement.",
    wsPlatformTitle: "Platform",
    wsPlatformText: "Linux-first, browser-based dashboard with local tooling.",
    wsDirectionTitle: "Direction",
    wsDirectionText: "Simple interface, clear diagnostics and fast access to important actions.",
    wsFeaturesEyebrow: "Core features",
    wsFeaturesTitle: "What it is being built to do.",
    wsFeatureSystemTitle: "System status",
    wsFeatureSystemText: "CPU, RAM, disk, temperature, internet and general machine state in one place.",
    wsFeatureMaintenanceTitle: "Maintenance",
    wsFeatureMaintenanceText: "Quick access to useful scripts, updates, checks and future repair/diagnostic actions.",
    wsFeatureLauncherTitle: "Project launcher",
    wsFeatureLauncherText: "Fast access to active local projects, development folders, GitHub repositories and tools.",
    wsFeatureDiagnosticsTitle: "Plain-language diagnostics",
    wsFeatureDiagnosticsText: "Technical information presented in a way that is useful without being buried in terminal output.",
    wsRoadmapEyebrow: "Roadmap",
    wsRoadmapTitle: "Next direction.",
    wsRoadmapOne: "Stabilise the dashboard structure and core system cards.",
    wsRoadmapTwo: "Improve diagnostics and make technical status easier to understand.",
    wsRoadmapThree: "Add safer maintenance actions with clear confirmations.",
    wsRoadmapFour: "Connect project documentation, scripts and GitHub workflow.",
    wsRoadmapFive: "Prepare a cleaner product identity under PJCore Labs.",

    ppEyebrow: "Projects",
    ppHeroTitle: "Ideas into reality.",
    ppHeroSubtitle: "PJCore Labs brings together practical digital projects, learning tools, automation systems and experimental products.",
    ppPortfolioEyebrow: "Project portfolio",
    ppPortfolioTitle: "Main projects",
    statusDevelopment: "In development",
    statusOnline: "Online",
    statusPlanned: "Planned",
    openProject: "Open project",
    ppWorkstationText: "A personal workstation control system for monitoring, maintenance, productivity and access to local projects.",
    ppSolicitadoriaText: "An independent educational legal study repository in Portuguese, with structured lessons, legal sources and academic progression.",
    ppLeisUkText: "A practical Portuguese-language guide to UK laws and public information, with official sources and clear disclaimers.",
    ppAiText: "A curated collection of useful AI tools, organised for practical use, discovery and quick reference.",

    rsEyebrow: "Project",
    rsHeroTitle: "Repositório de Solicitadoria",
    rsHeroSubtitle: "An independent educational legal study repository in Portuguese, with structured lessons, legal sources and academic progression.",
    rsOpenSiteButton: "Open website",
    rsPurposeEyebrow: "Purpose",
    rsPurposeTitle: "A structured legal study repository.",
    rsPurposeText: "Repositório de Solicitadoria organises legal study materials, lessons, summaries, quizzes and official legal sources into a clear academic path.",
    rsStatusTitle: "Status",
    rsStatusText: "Online and in active development.",
    rsFocusTitle: "Focus",
    rsFocusText: "Portuguese legal education, structured by subjects, lessons and study progression.",
    rsDisclaimerTitle: "Legal position",
    rsDisclaimerText: "Educational project only. It is not legal advice and does not replace qualified legal support.",
    rsDirectionTitle: "Direction",
    rsDirectionText: "Clearer lessons, better navigation, stronger legal sources and practical revision tools.",
    rsFeaturesEyebrow: "Core features",
    rsFeaturesTitle: "What the project provides.",
    rsFeatureLessonsTitle: "Structured lessons",
    rsFeatureLessonsText: "Subjects are organised into lessons, with progression across the academic path.",
    rsFeatureSourcesTitle: "Legal sources",
    rsFeatureSourcesText: "Official legal references and source links are used to support the material.",
    rsFeatureRevisionTitle: "Revision tools",
    rsFeatureRevisionText: "Quizzes, summaries and study support pages help with review and consolidation.",
    rsFeatureProgressTitle: "Academic progression",
    rsFeatureProgressText: "The repository tracks subjects, lessons and completion across the wider study plan.",

    ukEyebrow: "Project",
    ukHeroTitle: "Leis UK para Portugueses",
    ukHeroSubtitle: "A practical Portuguese-language guide to UK laws and public information, with official sources and clear disclaimers.",
    ukPurposeEyebrow: "Purpose",
    ukPurposeTitle: "Clear UK legal information for Portuguese speakers.",
    ukPurposeText: "Leis UK para Portugueses is designed to explain public legal information from the United Kingdom in Portuguese, using official sources and practical language.",
    ukStatusTitle: "Status",
    ukStatusText: "Planned and in preparation.",
    ukFocusTitle: "Focus",
    ukFocusText: "UK public information, legal rules and practical explanations for Portuguese-speaking readers.",
    ukSourcesTitle: "Sources",
    ukSourcesText: "The project will prioritise official sources, legislation and public authority guidance.",
    ukDisclaimerTitle: "Legal position",
    ukDisclaimerText: "Educational information only. It is not legal advice and does not replace a solicitor, adviser or qualified professional.",
    ukFeaturesEyebrow: "Core principles",
    ukFeaturesTitle: "How the project should work.",
    ukFeatureLanguageTitle: "Portuguese explanations",
    ukFeatureLanguageText: "Complex public information should be translated into clear Portuguese without distorting the legal meaning.",
    ukFeatureOfficialTitle: "Official references",
    ukFeatureOfficialText: "Each topic should link directly to the official source or legal rule being explained.",
    ukFeaturePracticalTitle: "Practical structure",
    ukFeaturePracticalText: "Subjects should be divided into smaller pages, so each rule can be explained carefully and checked properly.",
    ukFeatureHonestyTitle: "Clear limits",
    ukFeatureHonestyText: "The project must clearly separate educational information from professional legal advice.",

    aiEyebrow: "Project",
    aiHeroTitle: "AI Encyclopedia",
    aiHeroSubtitle: "A curated collection of useful AI tools, organised for practical use, discovery and quick reference.",
    aiOpenSiteButton: "Open website",
    aiPurposeEyebrow: "Purpose",
    aiPurposeTitle: "A practical directory of AI tools.",
    aiPurposeText: "AI Encyclopedia organises useful artificial intelligence tools into a simple reference space for discovery, comparison and daily use.",
    aiStatusTitle: "Status",
    aiStatusText: "Online and available for public use.",
    aiFocusTitle: "Focus",
    aiFocusText: "Useful AI tools, organised by practical purpose instead of hype.",
    aiUseTitle: "Use case",
    aiUseText: "Fast discovery of tools for writing, coding, productivity, research, image generation and learning.",
    aiDirectionTitle: "Direction",
    aiDirectionText: "Cleaner categories, better descriptions, favourites and practical recommendations.",
    aiFeaturesEyebrow: "Core features",
    aiFeaturesTitle: "What the project provides.",
    aiFeatureDirectoryTitle: "Tool directory",
    aiFeatureDirectoryText: "A curated list of useful AI tools grouped for practical use.",
    aiFeatureDiscoveryTitle: "Discovery",
    aiFeatureDiscoveryText: "A quick way to find tools that may help with real tasks and workflows.",
    aiFeatureSimpleTitle: "Simple navigation",
    aiFeatureSimpleText: "The project keeps the interface direct, lightweight and easy to browse.",
    aiFeaturePracticalTitle: "Practical selection",
    aiFeaturePracticalText: "The focus is usefulness, not collecting every tool that appears online.",

    footerText: "All rights reserved."
  }
};

function detectLanguage() {
  const saved = localStorage.getItem("pjcorelabs-language");
  if (saved) return saved;

  const browserLang = navigator.language || navigator.userLanguage || "en";

  if (browserLang.toLowerCase().startsWith("pt")) {
    return "pt";
  }

  return "en";
}

function setLanguage(lang) {
  localStorage.setItem("pjcorelabs-language", lang);
  document.documentElement.lang = lang;

  document.querySelectorAll("[data-i18n]").forEach((element) => {
    const key = element.getAttribute("data-i18n");
    if (translations[lang] && translations[lang][key]) {
      element.textContent = translations[lang][key];
    }
  });

  document.querySelectorAll("[data-lang-button]").forEach((button) => {
    button.classList.toggle("active", button.dataset.langButton === lang);
  });
}

document.addEventListener("DOMContentLoaded", () => {
  const lang = detectLanguage();
  setLanguage(lang);

  document.querySelectorAll("[data-lang-button]").forEach((button) => {
    button.addEventListener("click", () => {
      setLanguage(button.dataset.langButton);
    });
  });
});
